[tool.poetry]
name = "tc_c2pa_py"
version = "0.1.0"
description = "The TC-C2PA-Py is python library which provide C2PA standard functionality."
authors = ["Starodubtcev Dmitriy"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.4.0"
cbor2 = "^5.6.3"
cryptography = "^42.0.5"
pytz = "^2024.1"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
