[project]
name = "c2pie"
version = "1.0.0a2"
description = "c2pie is a Python library that provides C2PA standard functionality."
readme = 'README.md'
authors = [ 
  { name="Tourmaline Core", email="contact@tourmalinecore.com" },
]
license-files = [
  "LICENSE"
]
requires-python = '>=3.10'
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    'Operating System :: Microsoft :: Windows',
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://github.com/TourmalineCore/c2pie"
Issues = "https://github.com/TourmalineCore/c2pie/issues"

[project.scripts]
c2pie = 'c2pie.main:main'

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
cbor2 = "^6.1.4"
cryptography = ">=50.0.0"
pypdf = "^6.15.0"
c2pa-python = ">=0.37.5"
requests = "^2.34.2"
pyasn1 = "^0.6.4"
pyasn1-modules = "^0.4.2"

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
pytest-cov = "^7.1.0"
ruff = "^0.16.1"
deptry = "^0.25.1"
pre-commit = "^4.6.1"
pytest-xdist = "^3.8.0"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "e2e: marks tests as e2e",
]
addopts = "-n auto"

[tool.coverage.run]
omit = [
  "*_test.py",
  "*/__init__.py",
]

[tool.coverage.report]
show_missing = true