const { RELEASE_RULES, CHANGELOG_TYPES } = require('./release.rules.cjs');

module.exports = {
    branches: [
        { name: 'master' },
        { name: 'release/*', prerelease: 'rc' },
        { name: 'develop', prerelease: 'alpha' },
    ],

    plugins: [
        [
            '@semantic-release/commit-analyzer',
            {
                preset: 'conventionalcommits',
                releaseRules: RELEASE_RULES,
            },
        ],
        [
            '@semantic-release/release-notes-generator',
            {
                preset: 'conventionalcommits',
                presetConfig: { types: CHANGELOG_TYPES },
            },
        ],
        [
            '@semantic-release/changelog',
            { changelogFile: 'CHANGELOG.md' },
        ],
        [
            '@semantic-release/exec', 
            {
                prepareCmd: 'poetry version ${nextRelease.version} && poetry build',
            }
        ],
        [
            '@semantic-release/git',
            {
                assets: ['CHANGELOG.md', 'pyproject.toml'],
                message:
                    'chore(release): ${nextRelease.version}\n\n' +
                    'Automatically generated by semantic-release\n\n' +
                    'skip-checks: true',
            },
        ],
        [
            '@semantic-release/github', 
            {
                assets: [{ path: 'dist/*' }],
            }
        ],
    ],
};
