line-length = 120
# don’t allow syntax/features newer than Python 3.10 for compatibility purposes
target-version = "py310"
exclude = [".env-example"]

[lint]
select = ["E", "F", "I", "B", "UP"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
