name: Package Publishing

on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  run-e2e-tests:
    name: Package publishing
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 'latest'

      - name: Run Poetry install
        run: |
          poetry lock && poetry install --no-interaction --no-ansi

      - name: Configure Repository Credentials
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build and Publish the Package        
        run: |
          poetry publish --build