name: Build Image

on:
  push:
    branches:
      - master
      - feature/*
  # to allow to wait for a docker image to be published to proceed in another workflow
  workflow_call:

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    outputs:
      dockerfile-changed: ${{ steps.check-dockerfile.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - name: Check for Dockerfile changes
        id: check-dockerfile
        run: |
          echo "Checking for Dockerfile changes.."
          changes=$(git diff --name-only HEAD^ HEAD | grep -E 'Dockerfile' || true)
          if [ -n "$changes" ]; then
            echo "Dockerfile has been changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in Dockerfile"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # About automatic token in this secret: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/tourmalinecore/${{ github.event.repository.name }}
          tags: |
            # minimal (short sha)
            type=sha
            # full length sha
            type=sha,format=long
            # set latest tag for default branch
            # https://github.com/docker/metadata-action/issues/171 explains how to tag latest only on default branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
  
