name: Secrets Detection

on:
  # Need to conduct detection on push so that secrets don't get commited to the remote repo
  push:

jobs:
  check-for-secrets:
    name: Check that there are no hard-coded secrets
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v3
        env:
          GITLEAKS_CONFIG: .gitleaks.toml