name: Secrets Detection

on:
  # Need to conduct detection on push so that secrets don't get commited to the remote repo
  push:

jobs:
  check-for-secrets:
    name: Check that there are no hard-coded secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Conduct secrets check 
        uses: pre-commit/action@v3.0.1