name: Secrets Detection

on:
  push:

jobs:
  check-for-secrets:
    name: Check that there are no hard-coded secrets
    runs-on: ubuntu-atest
    steps:

      - uses: actions/checkouts@v4

      - uses: pre-commit/action@v3.0.1