name: E2E Testing on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run-e2e-tests:
      strategy: 
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

      defaults:
        run:
          shell: bash

      runs-on: ${{ matrix.os }}
      timeout-minutes: 30
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v5
        
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
            version: '2.4.1'
            virtualenvs-create: true
            virtualenvs-in-project: true

        - name: Load cached venv
          id: cached-poetry-dependencies
          uses: actions/cache@v4
          with:
            path: .venv
            key: venv-tests-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

        - name: Install dependencies
          run: poetry install --no-interaction

        - name: Install Rust toolchain and c2patool
          uses: baptiste0928/cargo-install@v3
          with:
            crate: c2patool
 
        - name: Verify if c2patool is installed 
          run: |
            c2patool -V

        - name: Run e2e tests with coverage
          run: |
            poetry run pytest tests/c2pa/e2e_test.py -v
          env:
            C2PIE_PRIVATE_KEY_FILE: ${{ vars.C2PIE_PRIVATE_KEY_FILE }}
            C2PIE_CERTIFICATE_CHAIN_FILE: ${{ vars.C2PIE_CERTIFICATE_CHAIN_FILE }}
