name: Run unit-tests

on:
  pull_request:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  run-unit-tests:
    name: Run unit tests (container)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/tourmalinecore/${{ github.event.repository.name }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build package
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/build_package.sh

      - name: Ensure pytest is available
        run: |
          if ! command -v pytest >/dev/null 2>&1; then
            python -m pip install -U pip pytest
          fi

      - name: Run unit tests
        run: |
          mkdir -p reports
          pytest --ignore=test_application -q --junitxml=reports/junit.xml --maxfail=1

      - name: Upload test report (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ github.sha }}
          path: reports/junit.xml
